# Generated by Django 2.1.7 on 2019-03-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数量')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='价格')),
            ],
            options={
                'verbose_name': '价格',
                'verbose_name_plural': '价格',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_price_item', to='goods.Price', verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shop',
            field=models.ManyToManyField(related_name='goods_shop_item', to='goods.Shop', verbose_name='商家'),
        ),
    ]
