# Generated by Django 2.1.7 on 2019-03-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='图片'),
        ),
    ]
