# Generated by Django 2.1.7 on 2019-03-07 13:00

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='img', verbose_name='轮播图'),
        ),
    ]
