# Generated by Django 2.1.7 on 2019-03-07 15:44

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
