# Generated by Django 2.1.7 on 2019-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_order_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='描述'),
        ),
    ]
