# Generated by Django 2.1.7 on 2019-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='discount',
            field=models.CharField(choices=[('1', '促销'), ('2', '非促销')], default='1', max_length=32, verbose_name='是否促销'),
        ),
    ]
