# Generated by Django 2.1.7 on 2019-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_imagebootstrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebootstrap',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
